/**
* KimiQuotes App
* Mobilszoftver labor házi feladatának API-ja.
*
* OpenAPI spec version: 1.0.0
* Contact: tothbece@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package hu.bme.aut.android.kimiquotes.network.model


/**
 * 
 * @param id 
 * @param quote 
 * @param year 
 */
data class Quote (
    val id: kotlin.Long? = null,
    val quote: kotlin.String? = null,
    val year: kotlin.Long? = null
) {

}

