/**
* KimiQuotes App
* Mobilszoftver labor házi feladatának API-ja.
*
* OpenAPI spec version: 1.0.0
* Contact: tothbece@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package hu.bme.aut.android.kimiquotes.network.api

import hu.bme.aut.android.kimiquotes.network.model.Quote
import retrofit2.Response
import retrofit2.http.GET
import retrofit2.http.POST


interface QuoteApi{

    /**
    * Összes idézet lekérdezése
    * 
    * @return kotlin.Array<Quote>
    */
    @GET("quotes")
    suspend fun handleGetQuotes() : Response<Array<Quote>>

    /**
    * Véletlenszerű idézet lekérdezése
    * 
    * @return kotlin.Array<Quote>
    */
    @GET("quote")
    suspend fun handleGetRandomQuote() : Response<Quote>

    /**
    * Új idézet felvétele
    * 
    * @param quote  (optional)
    * @return void
    */
    @POST("quote")
    suspend fun handlePostQuote(quote: Quote)

}
